config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :update] do
    collection do
      get :fetch_all
      get :fetch_result
    end
  end
  resources :favorities
  get 'dashboard' => 'home#dashboard'
  root 'posts#index'
end

app/models/favority.rb
class Favority
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short

  belongs_to :post

  validates :post_id, uniqueness: true
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short

  field :title,   type: String
  field :url,     type: String
  field :from,    type: String
  field :author,  type: String
  field :p_date,  type: String
  field :comment, type: String

  validates :title, :url, uniqueness: true
  scope :with_tag, ->(tag) { where(from: tag) }

  def self.all_tags
    [
      [:cb,  6],
      [:qd,  4],
      [:dfh, 4],
      [:hz,  2],
      [:qxz, 3],
      [:gzc, 3],
      [:bt,  3],
    ]
  end

end

app/models/progress.rb
class Progress
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short

  field :status, type: String
  field :fetch_count, type: Integer, default: 0

  before_create :set_status
  scope :doing, -> { where(status: 'new') }
  scope :has_done, -> { where(status: 'done') }

  def done!
    update status: 'done'
  end

  private

  def set_status
    self.status = 'new'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorities_controller.rb
class FavoritiesController < ApplicationController
  def index
    @favorities = Favority.order(c_at: :desc).page(params[:page]).includes(:post)
  end

  def create
    if Favority.create(post: Post.find(params[:p_id]))
      render json: { success: true }
    else
      render json: { success: false }, status: :failure
    end
  end

  def destroy
    if Favority.where(post_id: params[:id]).first.destroy
      render json: { success: true }
    else
      render json: { success: false }, status: :failure
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(title: /#{ params[:q] }/)
    @posts = @posts.where(from: params[:from]) if params[:from].present?
    @posts = @posts.order(c_at: :desc).page(params[:page])
  end

  def show
  end

  def update
    @post = Post.find(params[:id])
    if @post.update comment: params[:comment]
      head 200
    else
      head 403
    end
  end

  def fetch_all
    if Progress.doing.size > 0
      head 403
    else
      Thread.start do
        progress = Progress.create
        fetch_count = PostSpider.new.fetch_all
        progress.update fetch_count: fetch_count
        progress.done!
      end
      head 200
    end
  end

  def fetch_result
    render json: {
      done: Progress.doing.size == 0,
      fetch_count: Progress.has_done.last.try(:fetch_count),
      last_time: Progress.has_done.last.try(:c_at).strftime('%m/%d %H:%M:%S')
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorities_helper.rb
module FavoritiesHelper
  def post_favority_class(post)
    Favority.where(post_id: post.id).exists? ? 'has_fav' : 'wasnt_fav'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html">HEHE Spider</a>
  </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-messages">
            <% Progress.order(c_at: :desc).limit(5).each do |progress| %>
              <li>
              <a href="#">
                <div>
                  <strong>Task</strong>
                  <span class="pull-right text-muted">
                    <em><%= time_ago_in_words progress.c_at %></em>
                  </span>
                </div>
                <div>Fetch <%= progress.fetch_count %> Items, Totaly</div>
              </a>
              </li>
              <li class="divider"></li>
            <% end %>
            <%#<li>%>
            <%#<a class="text-center" href="#">%>
              <%#<strong>Read All Messages</strong>%>
              <%#<i class="fa fa-angle-right"></i>%>
            <%#</a>%>
            <%#</li>%>
          </ul>
          <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
              <li>
              <a href="#">
                <div id='post-progressbar'>
                  <p>
                  <strong>Task</strong>
                  <span class="pull-right text-muted progress-pre">100% Complete</span>
                  </p>
                  <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                      <span class="sr-only">40% Complete (success)</span>
                    </div>
                  </div>
                  <p>
                  <span class="text-muted time">Last At: <%= Progress.has_done.last.try(:c_at).strftime('%m/%d %H:%M:%S') %>, Fetch: <%= Progress.has_done.last.try(:fetch_count) %> Items</span>
                  </p>
                </div>
              </a>
              <li class="divider"></li>
              <li>
                <%= link_to fetch_all_posts_path, remote: true, class: 'text-center fetch-all-posts-btn' do %>
                  <strong>Fetch Items</strong>
                  <i class="fa fa-angle-right"></i>
                <% end %>
              </li>
            </ul>
            <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
              <li>
                <a href="#">
                  <div>
                    <i class="fa fa-comment fa-fw"></i> New Comment
                    <span class="pull-right text-muted small">4 minutes ago</span>
                  </div>
                </a>
              </li>
              <li class="divider"></li>
              <li>
                <a class="text-center" href="#">
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </li>
            </ul>
            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li class="sidebar-search">
          <form class='input-group custom-search-form' action="/" method="get" accept-charset="utf-8">
            <input type="text" name='q' class="form-control" placeholder="Search..." value="<%= params[:q] %>">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </form>
          </li>
          <li>
          <a href="/dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
          </li>
          <li>
          <a href="/"><i class="fa fa-dashboard fa-fw"></i> 所有</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:controller] == 'favorities' %>" href="/favorities"><i class="fa fa-shopping-cart fa-fw"></i> 收藏的</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:from] == 'hz_bike' %>" href="/?from=hz_bike"><i class="fa fa-table fa-fw"></i> 骑友网</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:from] == 'qd_bike' %>" href="/?from=qd_bike"><i class="fa fa-table fa-fw"></i> 起点</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:from] == 'cb_bike' %>" href="/?from=cb_bike"><i class="fa fa-table fa-fw"></i> ChinaBike</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:from] == 'dfh_bike' %>" href="/?from=dfh_bike"><i class="fa fa-table fa-fw"></i> 东方红</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:from] == 'qxz_bike' %>" href="/?from=qxz_bike"><i class="fa fa-table fa-fw"></i> 骑行者</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:from] == 'gzc_bike' %>" href="/?from=gzc_bike"><i class="fa fa-table fa-fw"></i> GZC</a>
          </li>
          <li>
          <a class="<%= 'active' if params[:from] == 'bt_bike' %>" href="/?from=bt_bike"><i class="fa fa-table fa-fw"></i> BikeTo</a>
          </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/favorities/index.html.erb
<%= paginate @favorities %>
<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>标题</th>
      <th>发布时间</th>
      <th>抓取时间</th>
      <th>出处</th>
      <th>操作</th>
      <th>备注</th>
    </tr>
  </thead>
  <tbody>
    <% @favorities.each do |favory| %>
      <%- post = favory.post %>
      <tr>
        <td>
          <%= link_to truncate(post.title), post.url, target: '_blank', class: 'post-title', data: { toggle: 'tooltip', placement: 'top' }, title: post.title %>
        </td>
        <td><%= post.p_date %></td>
        <td><%= post.c_at.strftime('%m/%d %H:%M') %></td>
        <td><%= post.from.split('_').first %></td>
        <td class='<%= post_favority_class(post) %>'>
          <%= link_to 'Favour', favorities_path(p_id: post.id), remote: true, method: :post, class: 'favory' %>
          <%= link_to 'UnFavour', favority_path(id: post.id), remote: true, method: :delete, class: 'unfavory' %>
        </td>
        <td data-id="<%= post.id %>" class='post-comment'><%= post.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @favorities %>

app/views/home/dashboard.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Dashboard</h1>
  </div>
</div>

<div class="row">
  <% Post.all_tags.each do |from, _| %>
    <div class="col-lg-3 col-md-6">
      <div class="panel <%= cycle('panel-primary', 'panel-green', 'panel-yellow', 'panel-red') %>">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="fa fa-tasks fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge"><%= Post.with_tag("#{ from }_bike").count  %></div>
              <div><%= from.to_s.humanize %></div>
            </div>
          </div>
        </div>
        <a href="/?from=<%= from %>_bike">
          <div class="panel-footer">
            <span class="pull-left">View All</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        </a>
      </div>
    </div>
  <% end %>
</div>

<div class='row'>
    <div class="col-lg-3 col-md-6">
      <div class="panel panel-yellow">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="fa fa-shopping-cart fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge"><%= Favority.count  %></div>
              <div>收藏</div>
            </div>
          </div>
        </div>
        <a href="/favorities">
          <div class="panel-footer">
            <span class="pull-left">View All</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        </a>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BikeSpider</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="wrapper">
    <%= render partial: 'nav' %>
    <div id="page-wrapper">
      <%#<div class="row">%>
        <%#<div class="col-lg-12">%>
          <%#<h1 class="page-header">Oooooop~ Bike Spider</h1>%>
        <%#</div>%>
      <%#</div>%>
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/index.html.erb
<%= paginate @posts %>
<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>N.</th>
      <th>标题</th>
      <th>发布时间</th>
      <th>抓取时间</th>
      <th>出处</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each_with_index do |post, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td>
          <%= link_to truncate(post.title), post.url, target: '_blank', class: 'post-title', data: { toggle: 'tooltip', placement: 'top' }, title: post.title %>
        </td>
        <td><%= post.p_date %></td>
        <td><%= post.c_at.strftime('%m/%d %H:%M') %></td>
        <td><%= post.from.split('_').first %></td>
        <td class='<%= post_favority_class(post) %>'>
          <%= link_to 'Favour', favorities_path(p_id: post.id), remote: true, method: :post, class: 'favory' %>
          <%= link_to 'UnFavour', favority_path(id: post.id), remote: true, method: :delete, class: 'unfavory' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @posts %>

app/views/posts/show.html.erb
<table border="0">
  <tbody>
    <tr>
      <th>标题：</th>
      <td><%= link_to @post.title, @post.url %></td>
    </tr>
  </tbody>
</table>